<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Modelos Lineales | AnalisisdeDatos.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Modelos Lineales | AnalisisdeDatos.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Modelos Lineales | AnalisisdeDatos.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="exploracion-y-visualización-de-datos.html"/>
<link rel="next" href="herramientas-para-visualizar-datos.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="index.html#section" id="toc-section"></a></li>
<li class="chapter" data-level="1" data-path="correlaciones-y-graficos-con-correlaciones.html"><a href="correlaciones-y-graficos-con-correlaciones.html"><i class="fa fa-check"></i><b>1</b> Correlaciones y graficos con correlaciones</a>
<ul>
<li class="chapter" data-level="1.1" data-path="correlaciones-y-graficos-con-correlaciones.html"><a href="correlaciones-y-graficos-con-correlaciones.html#qué-tipo-de-objeto-es-c"><i class="fa fa-check"></i><b>1.1</b> ¿Qué tipo de objeto es c?</a></li>
<li class="chapter" data-level="1.2" data-path="correlaciones-y-graficos-con-correlaciones.html"><a href="correlaciones-y-graficos-con-correlaciones.html#pasamos-a-la-sección-de-modelaje."><i class="fa fa-check"></i><b>1.2</b> Pasamos a la sección de modelaje.</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="practica-utilizando-astasa-anexos.html"><a href="practica-utilizando-astasa-anexos.html"><i class="fa fa-check"></i><b>2</b> Practica utilizando astasa (Anexos)</a></li>
<li class="chapter" data-level="3" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html"><i class="fa fa-check"></i><b>3</b> Exploracion y Visualización de Datos</a>
<ul>
<li class="chapter" data-level="3.1" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#exploración-de-datos"><i class="fa fa-check"></i><b>3.1</b> Exploración de datos</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#que-interesa-conocer-de-los-datos"><i class="fa fa-check"></i><b>3.1.1</b> ¿Que interesa conocer de los datos?</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#una-mirada-a-los-datos"><i class="fa fa-check"></i><b>3.2</b> Una mirada a los datos</a></li>
<li class="chapter" data-level="3.3" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#atipicidades"><i class="fa fa-check"></i><b>3.3</b> Atipicidades</a></li>
<li class="chapter" data-level="3.4" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#una-mirada-a-las-correlaciones"><i class="fa fa-check"></i><b>3.4</b> Una mirada a las correlaciones</a></li>
<li class="chapter" data-level="3.5" data-path="exploracion-y-visualización-de-datos.html"><a href="exploracion-y-visualización-de-datos.html#bases-para-la-regresion"><i class="fa fa-check"></i><b>3.5</b> Bases para la regresion</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelos-lineales.html"><a href="modelos-lineales.html"><i class="fa fa-check"></i><b>4</b> Modelos Lineales</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelos-lineales.html"><a href="modelos-lineales.html#modelo-lineal-general"><i class="fa fa-check"></i><b>4.1</b> Modelo lineal general</a></li>
<li class="chapter" data-level="4.2" data-path="modelos-lineales.html"><a href="modelos-lineales.html#qué-es-un-modelo"><i class="fa fa-check"></i><b>4.2</b> ¿Qué es un modelo?</a></li>
<li class="chapter" data-level="4.3" data-path="modelos-lineales.html"><a href="modelos-lineales.html#regresion-lineal-simple"><i class="fa fa-check"></i><b>4.3</b> Regresion lineal simple</a></li>
<li class="chapter" data-level="4.4" data-path="modelos-lineales.html"><a href="modelos-lineales.html#supuesto-de-normalidad"><i class="fa fa-check"></i><b>4.4</b> Supuesto de Normalidad</a></li>
<li class="chapter" data-level="4.5" data-path="modelos-lineales.html"><a href="modelos-lineales.html#supuesto-de-homocedasticidad-de-varianzas"><i class="fa fa-check"></i><b>4.5</b> Supuesto de Homocedasticidad de varianzas</a></li>
<li class="chapter" data-level="4.6" data-path="modelos-lineales.html"><a href="modelos-lineales.html#supuesto-de-independencia"><i class="fa fa-check"></i><b>4.6</b> Supuesto de Independencia</a></li>
<li class="chapter" data-level="4.7" data-path="modelos-lineales.html"><a href="modelos-lineales.html#tecnicas-para-corregir-la-heterocedasticidad-de-varianzas"><i class="fa fa-check"></i><b>4.7</b> Tecnicas para corregir la heterocedasticidad de varianzas</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="herramientas-para-visualizar-datos.html"><a href="herramientas-para-visualizar-datos.html"><i class="fa fa-check"></i><b>5</b> Herramientas para visualizar datos</a>
<ul>
<li class="chapter" data-level="5.1" data-path="herramientas-para-visualizar-datos.html"><a href="herramientas-para-visualizar-datos.html#chunk-de-librerías"><i class="fa fa-check"></i><b>5.1</b> Chunk de librerías</a></li>
<li class="chapter" data-level="5.2" data-path="herramientas-para-visualizar-datos.html"><a href="herramientas-para-visualizar-datos.html#carga-de-la-base-de-datos"><i class="fa fa-check"></i><b>5.2</b> Carga de la base de datos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="visualización-de-datos-con-ggplot2.html"><a href="visualización-de-datos-con-ggplot2.html"><i class="fa fa-check"></i><b>6</b> Visualización de Datos con ggplot2</a></li>
<li class="chapter" data-level="7" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html"><i class="fa fa-check"></i><b>7</b> Gráficos de Barras</a>
<ul>
<li class="chapter" data-level="7.1" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html#requerimientos"><i class="fa fa-check"></i><b>7.1</b> Requerimientos:</a></li>
<li class="chapter" data-level="7.2" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html#legend-siempre-nos-pide-los-siguientes-argumentos."><i class="fa fa-check"></i><b>7.2</b> legend() siempre nos pide los siguientes argumentos.</a></li>
<li class="chapter" data-level="7.3" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html#grafico-de-pastel"><i class="fa fa-check"></i><b>7.3</b> Grafico de pastel</a></li>
<li class="chapter" data-level="7.4" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html#gráfico-de-dona"><i class="fa fa-check"></i><b>7.4</b> Gráfico de dona</a></li>
<li class="chapter" data-level="7.5" data-path="gráficos-de-barras.html"><a href="gráficos-de-barras.html#para-practicar"><i class="fa fa-check"></i><b>7.5</b> Para practicar</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="diagramas-de-cajas-boxplots.html"><a href="diagramas-de-cajas-boxplots.html"><i class="fa fa-check"></i><b>8</b> Diagramas de cajas (Boxplots)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="diagramas-de-cajas-boxplots.html"><a href="diagramas-de-cajas-boxplots.html#chunk-para-librerías"><i class="fa fa-check"></i><b>8.1</b> Chunk para librerías</a></li>
<li class="chapter" data-level="8.2" data-path="diagramas-de-cajas-boxplots.html"><a href="diagramas-de-cajas-boxplots.html#pie-chart"><i class="fa fa-check"></i><b>8.2</b> Pie Chart</a></li>
<li class="chapter" data-level="8.3" data-path="diagramas-de-cajas-boxplots.html"><a href="diagramas-de-cajas-boxplots.html#paleta-de-colores"><i class="fa fa-check"></i><b>8.3</b> Paleta de colores</a></li>
<li class="chapter" data-level="8.4" data-path="diagramas-de-cajas-boxplots.html"><a href="diagramas-de-cajas-boxplots.html#diagrama-de-cajas"><i class="fa fa-check"></i><b>8.4</b> Diagrama de cajas</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelos-lineales" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Modelos Lineales<a href="modelos-lineales.html#modelos-lineales" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="modelo-lineal-general" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Modelo lineal general<a href="modelos-lineales.html#modelo-lineal-general" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La regresión es un modelo lineal general que puede considerarse como el origen de muchos de los modelos que se usan en estadística.</p>
</div>
<div id="qué-es-un-modelo" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> ¿Qué es un modelo?<a href="modelos-lineales.html#qué-es-un-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Un modelo es una descripción generalizada para analizar o explicar algo, comparamos (confrontamos) modelos con datos, evaluamos el ajuste de modelos a los datos observados</p>
<p><strong>Tipos de modelos lineales generales</strong></p>
<ul>
<li><p>Regresión lineal simple</p></li>
<li><p>Regresión lineal múltiple</p></li>
<li><p>Anova (Análisis de varianza)</p></li>
<li><p>Ancova (Análisis de covarainza)</p></li>
</ul>
</div>
<div id="regresion-lineal-simple" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Regresion lineal simple<a href="modelos-lineales.html#regresion-lineal-simple" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La regresión lineal simple describe la relación entre una <strong>variable respuesta</strong> (variable dependiente) y una <strong>variable explicativa</strong> (variable independiente).</p>
<p>A diferencia de la correlación, donde las variables no se consideran variable respuesta o explicativa, en la regresión simple debe estar muy claro cual es la variable respuesta y cual es la variable explicativa. Por ejemplo, el peso corporal puede tener un efecto sobre la presión sanguínea, pero la presión sanguínea no puede tener un efecto sobre el peso corporal. Está muy claro quien es la varibale respuesta y cual la variable explicativa.</p>
<p>Propósitos del modelo de regresión:</p>
<ul>
<li><p><strong>Descripción:</strong> describir la relación entre la variable respuesta (<span class="math inline">\(Y\)</span>) y la variable explicatoria (<span class="math inline">\(X\)</span>)</p></li>
<li><p><strong>Explicación:</strong> cuantificar la variación de <span class="math inline">\(Y\)</span> explicada por la relación con <span class="math inline">\(X\)</span></p></li>
<li><p><strong>Predicción:</strong> predecir nuevos valores de <span class="math inline">\(Y\)</span> basados en nuevos valores de <span class="math inline">\(X\)</span></p></li>
</ul>
<p>Veamos un modelo de regresión simple, pero antes, carguemos los paquetes que utilizaremos en este análisis:</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb120-1"><a href="modelos-lineales.html#cb120-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb120-2"><a href="modelos-lineales.html#cb120-2" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb120-3"><a href="modelos-lineales.html#cb120-3" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb120-4"><a href="modelos-lineales.html#cb120-4" tabindex="-1"></a><span class="fu">library</span>(parameters)</span>
<span id="cb120-5"><a href="modelos-lineales.html#cb120-5" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb120-6"><a href="modelos-lineales.html#cb120-6" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb120-7"><a href="modelos-lineales.html#cb120-7" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb120-8"><a href="modelos-lineales.html#cb120-8" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb120-9"><a href="modelos-lineales.html#cb120-9" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb120-10"><a href="modelos-lineales.html#cb120-10" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span>
<span id="cb120-11"><a href="modelos-lineales.html#cb120-11" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code></pre></div>
<p>Cargamos los datos trees que se incluyen en <code>R</code>.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="modelos-lineales.html#cb121-1" tabindex="-1"></a><span class="fu">data</span>(trees)</span></code></pre></div>
<p>Estos datos contienen las siguientes medidas de árboles:</p>
<ul>
<li><p><strong>Girth:</strong> diámetro a la altura del pecho de los árboles en pulgadas</p></li>
<li><p><strong>Height:</strong> altura de los árboles en pies</p></li>
<li><p><strong>Volume:</strong> volumen de los árboles en pies cúbicos</p></li>
</ul>
<p>Lo que vamos a hacer es cambiar el nombre del conjunto de datos arboles y crear nuevas variables en español y con el sistema métrico decimal, para ellos utilizaremos la función <em>mutate</em> del paquete <code>dplyr</code> (<code>tidyverse</code>)</p>
<p>Con la función <em>mutate()</em> podemos computar tranformaciones de variables en un data frame. A menudo, tendremos la necesidad de crear nuevas variables que se calculan a partir de variables existentes.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb122-1"><a href="modelos-lineales.html#cb122-1" tabindex="-1"></a>arboles <span class="ot">&lt;-</span> trees <span class="sc">%&gt;%</span></span>
<span id="cb122-2"><a href="modelos-lineales.html#cb122-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dap =</span> Girth<span class="sc">*</span><span class="fl">2.54</span>, <span class="co"># de pulgadas a centímetros</span></span>
<span id="cb122-3"><a href="modelos-lineales.html#cb122-3" tabindex="-1"></a>         <span class="at">altura =</span> Height<span class="sc">/</span><span class="fl">3.281</span>, <span class="co"># de pies a metros</span></span>
<span id="cb122-4"><a href="modelos-lineales.html#cb122-4" tabindex="-1"></a>         <span class="at">volumen =</span> Volume<span class="sc">/</span><span class="fl">35.315</span>) <span class="co"># de pies cúbicos a metros cúbicos</span></span>
<span id="cb122-5"><a href="modelos-lineales.html#cb122-5" tabindex="-1"></a>arboles <span class="ot">&lt;-</span> arboles[, <span class="fu">c</span>(<span class="st">&quot;dap&quot;</span>, <span class="st">&quot;volumen&quot;</span>,<span class="st">&quot;altura&quot;</span>)]</span></code></pre></div>
<p>Ahora tenemos 3 nuevas variables:</p>
<ul>
<li><p><strong>dap:</strong> diámetro a la altura del pecho en centímetros</p></li>
<li><p><strong>altura:</strong> altura de los árboles en metros</p></li>
<li><p><strong>volumen:</strong> volumen de los árboles en metros cúbicos</p></li>
</ul>
<p>Veamos los datos. Con la función <em>head</em> podemos ver las primeras 6 filas de los datos</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="modelos-lineales.html#cb123-1" tabindex="-1"></a><span class="fu">head</span>(arboles)</span></code></pre></div>
<pre><code>##      dap   volumen   altura
## 1 21.082 0.2916608 21.33496
## 2 21.844 0.2916608 19.81103
## 3 22.352 0.2888291 19.20146
## 4 26.670 0.4643919 21.94453
## 5 27.178 0.5323517 24.68760
## 6 27.432 0.5578366 25.29717</code></pre>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="modelos-lineales.html#cb125-1" tabindex="-1"></a><span class="fu">str</span>(arboles)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    31 obs. of  3 variables:
##  $ dap    : num  21.1 21.8 22.4 26.7 27.2 ...
##  $ volumen: num  0.292 0.292 0.289 0.464 0.532 ...
##  $ altura : num  21.3 19.8 19.2 21.9 24.7 ...</code></pre>
<p>Graficamos los datos usando el <em>dap</em> (diámetro a la altura del pecho) en el eje de las <span class="math inline">\(x\)</span> (abscisas) y el <em>volumen</em> en el eje de las <span class="math inline">\(y\)</span> (ordenadas).</p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="modelos-lineales.html#cb127-1" tabindex="-1"></a><span class="fu">ggplot</span>(arboles, <span class="fu">aes</span>(dap, volumen)) <span class="sc">+</span></span>
<span id="cb127-2"><a href="modelos-lineales.html#cb127-2" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb127-3"><a href="modelos-lineales.html#cb127-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;dodgerblue3&quot;</span>)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-92-1.png" width="672" /></p>
<p>Echemos un vistaso a las correlaciones entre las variables:</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="modelos-lineales.html#cb128-1" tabindex="-1"></a><span class="fu">pairs.panels</span>(arboles, <span class="at">scale=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-93-1.png" width="672" /></p>
<p>Vamos a ajustar un modelo lineal general, es decir una regresión lineal simple. Para eso usamos la función <em>lm</em> (linear model)</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="modelos-lineales.html#cb129-1" tabindex="-1"></a>regresion_simple <span class="ot">&lt;-</span> <span class="fu">lm</span>(volumen <span class="sc">~</span> dap, <span class="at">data =</span> arboles)</span>
<span id="cb129-2"><a href="modelos-lineales.html#cb129-2" tabindex="-1"></a>regresion_simple</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = volumen ~ dap, data = arboles)
## 
## Coefficients:
## (Intercept)          dap  
##    -1.04611      0.05648</code></pre>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="modelos-lineales.html#cb131-1" tabindex="-1"></a><span class="fu">summary</span>(regresion_simple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = volumen ~ dap, data = arboles)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.228383 -0.087971  0.004303  0.098960  0.271466 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.046112   0.095289  -10.98 7.62e-12 ***
## dap          0.056475   0.002758   20.48  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1204 on 29 degrees of freedom
## Multiple R-squared:  0.9353, Adjusted R-squared:  0.9331 
## F-statistic: 419.4 on 1 and 29 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="modelos-lineales.html#cb133-1" tabindex="-1"></a>regresion_simple<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>## (Intercept)         dap 
## -1.04611239  0.05647548</code></pre>
<p>Primero veamos lo que está pasando gráficamente</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="modelos-lineales.html#cb135-1" tabindex="-1"></a><span class="fu">ggplot</span>(arboles, <span class="fu">aes</span>(dap, volumen)) <span class="sc">+</span></span>
<span id="cb135-2"><a href="modelos-lineales.html#cb135-2" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb135-3"><a href="modelos-lineales.html#cb135-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;dodgerblue3&quot;</span>) <span class="sc">+</span></span>
<span id="cb135-4"><a href="modelos-lineales.html#cb135-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-97-1.png" width="672" /></p>
<p>La línea de color rojo representa el modelo de regresión ajustado a los datos. Matemáticamente, podemos escribir la ecuación del modelo de regresión de la siguiente manera:</p>
<p><span class="math inline">\(Y \approx\beta _0+ \beta _1X+ \varepsilon\)</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(Y\)</span> representa a la variable respuesta</li>
<li><span class="math inline">\(X\)</span> representa la variables explicativa</li>
<li><span class="math inline">\(\beta _0\)</span> es el intercepto del modelo</li>
<li><span class="math inline">\(\beta _1\)</span> la pendiente del modelo</li>
<li><span class="math inline">\(\varepsilon\)</span> es el error, término que significa la variabilidad de <span class="math inline">\(Y\)</span> que el modelo no puede explicar (lo que <span class="math inline">\(X\)</span> no puede decirnos sobre <span class="math inline">\(Y\)</span>)</li>
</ul>
<p>En nuestro ejemplo, <span class="math inline">\(volumen ≈ intercepto + pendiente(dap) + error\)</span></p>
<p>Veamos un resumen numérico del modelo</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="modelos-lineales.html#cb137-1" tabindex="-1"></a><span class="fu">summary</span>(regresion_simple)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = volumen ~ dap, data = arboles)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.228383 -0.087971  0.004303  0.098960  0.271466 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -1.046112   0.095289  -10.98 7.62e-12 ***
## dap          0.056475   0.002758   20.48  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1204 on 29 degrees of freedom
## Multiple R-squared:  0.9353, Adjusted R-squared:  0.9331 
## F-statistic: 419.4 on 1 and 29 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Seguidamente, echemos una mirada a los residuales del modelo.</p>
<p>Calculemos estos valores y posteriormente, los agregaremos al gráfico:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="modelos-lineales.html#cb139-1" tabindex="-1"></a>arboles<span class="sc">$</span>predicho <span class="ot">&lt;-</span> <span class="fu">predict</span>(regresion_simple) <span class="co"># guardamos los valores predicho por el modelo</span></span></code></pre></div>
<p>Seguidamente mostraremos el gáfico con datos crudos y los valores predichos:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="modelos-lineales.html#cb140-1" tabindex="-1"></a><span class="fu">ggplot</span>(arboles, <span class="fu">aes</span>(dap, volumen)) <span class="sc">+</span></span>
<span id="cb140-2"><a href="modelos-lineales.html#cb140-2" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb140-3"><a href="modelos-lineales.html#cb140-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb140-4"><a href="modelos-lineales.html#cb140-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb140-5"><a href="modelos-lineales.html#cb140-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> predicho), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-100-1.png" width="672" /></p>
<p>Representamos gráficamente los residuales:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="modelos-lineales.html#cb142-1" tabindex="-1"></a><span class="fu">ggplot</span>(arboles, <span class="fu">aes</span>(dap, volumen)) <span class="sc">+</span></span>
<span id="cb142-2"><a href="modelos-lineales.html#cb142-2" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb142-3"><a href="modelos-lineales.html#cb142-3" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> lm, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>) <span class="sc">+</span></span>
<span id="cb142-4"><a href="modelos-lineales.html#cb142-4" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb142-5"><a href="modelos-lineales.html#cb142-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> predicho), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb142-6"><a href="modelos-lineales.html#cb142-6" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> dap, <span class="at">yend =</span> predicho), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-101-1.png" width="672" /></p>
<p>Pero todos los modelos tienen supuestos</p>
<p>El modelo lineal general debe cumplir los siguientes supuestos para que el modelo sea interpretado y aplicado en la práctica.</p>
<p>Supuestos de un modelo lineal general</p>
<ul>
<li><ol style="list-style-type: decimal">
<li>Linealidad</li>
</ol></li>
<li><ol start="2" style="list-style-type: decimal">
<li>Normalidad</li>
</ol></li>
<li><ol start="3" style="list-style-type: decimal">
<li>Homogeneidad de varianza</li>
</ol></li>
<li><ol start="4" style="list-style-type: decimal">
<li>Independencia</li>
</ol></li>
</ul>
<p>Para verificar los supuestos debemos ver gráficos diagnósticos del modelo que permiten gráficar los residuales del modelo</p>
<p><strong>Linealidad</strong></p>
<p>Un modelo es lineal cuando cualquier valor de la variable dependiente o respuesta (<span class="math inline">\(y_i\)</span>) es descrita por una combinación lineal de una serie de parámetros (coeficientes de la pendiente, intercepto).</p>
<p><span class="math inline">\(Y \approx  \beta _0 + \beta _1X_1 + ... + \beta _n X_n + \varepsilon\)</span></p>
</div>
<div id="supuesto-de-normalidad" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Supuesto de Normalidad<a href="modelos-lineales.html#supuesto-de-normalidad" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Hace referencia a la normalidad de los residuales del modelo.</p>
<p>Este supuesto se puede estudiar de manera gráfica:</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="modelos-lineales.html#cb144-1" tabindex="-1"></a><span class="fu">check_model</span>(regresion_simple)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-102-1.png" width="672" /></p>
<p>Los 2 primeros gráficos sirven para verificar el supuesto de normalidad de los residuales</p>
<p>Los 2 gráficos del centro sirven para verificar el supuesto de la homogeneidad de la varianza</p>
<p>El último gráfico sirve para verificar si hay una observación influyente. Una observación influyente es una observación que tiene una distancia de Cook mayor a 1. En este caso la observación 31 está cerca de ser una observación influyente pero no lo es, o en este caso no es considerada influyente aunque tiene una distancia de Cook más lata que el resto pero no supera el valor de 1.</p>
<p>Miremos los gráficos de manera individual:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="modelos-lineales.html#cb145-1" tabindex="-1"></a><span class="fu">check_model</span>(regresion_simple, <span class="at">check =</span> <span class="st">&quot;normality&quot;</span>)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-103-1.png" width="672" /></p>
<p>También numéricamente:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="modelos-lineales.html#cb146-1" tabindex="-1"></a><span class="fu">check_normality</span>(regresion_simple)</span></code></pre></div>
<pre><code>## OK: residuals appear as normally distributed (p = 0.718).</code></pre>
</div>
<div id="supuesto-de-homocedasticidad-de-varianzas" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Supuesto de Homocedasticidad de varianzas<a href="modelos-lineales.html#supuesto-de-homocedasticidad-de-varianzas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Extraemos el siguiente gráfico para mirar el comportamiento de los residuales:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="modelos-lineales.html#cb148-1" tabindex="-1"></a><span class="fu">check_model</span>(regresion_simple, <span class="at">check =</span> <span class="st">&quot;ncv&quot;</span>)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-105-1.png" width="672" /></p>
<p>Vemos que hay un incremento de la varianza en el último residual y se evidencia un patrón. Se puede verificar esto numéricamente:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="modelos-lineales.html#cb149-1" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(regresion_simple)</span></code></pre></div>
<pre><code>## Warning: Heteroscedasticity (non-constant error variance) detected (p = 0.043).</code></pre>
<p>Note que el resultado refuerza la conclusión observada en el gráfico, es decir, hay un problema de no homogeneidad de varianzas.</p>
</div>
<div id="supuesto-de-independencia" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Supuesto de Independencia<a href="modelos-lineales.html#supuesto-de-independencia" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Este supuesto se refiere a que los residuales deben ser independientes, es decir no estar autocorrelacionados. Los residuales están autocorrelacionados cuando las observaciones provienen de un diseño de muestreo que no permitió obtener observaciones independientes, es decir que el valor de una observación no depende de la anterior. esto es común en series de timepo, cuando una variable se mide a lo largo del tiempo.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="modelos-lineales.html#cb151-1" tabindex="-1"></a><span class="fu">check_autocorrelation</span>(regresion_simple)</span></code></pre></div>
<pre><code>## OK: Residuals appear to be independent and not autocorrelated (p = 0.078).</code></pre>
<p>Ahora pasemos a resolver el problema de la falta de homogeneidad de varianza</p>
</div>
<div id="tecnicas-para-corregir-la-heterocedasticidad-de-varianzas" class="section level2 hasAnchor" number="4.7">
<h2><span class="header-section-number">4.7</span> Tecnicas para corregir la heterocedasticidad de varianzas<a href="modelos-lineales.html#tecnicas-para-corregir-la-heterocedasticidad-de-varianzas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li><p><strong>Transformación de variables:</strong> la única que se recomienda logarítmica, pero las demás, no son buenas en la práctica por los problemas de interpretación que genera al modificar la variable. Los econometristas usan un modelos log - log aplicando log en ambos lados y se puede hacer una interpretación de tipo porcentual, cambio de porcentaje en el eje x, tiene un cambio en el porcentaje de y.</p></li>
<li><p><strong>Usar el paquete lmtest:</strong> los modelos siguientes corrigen la matriz de covarianzas, identificando el problema usando tecnicas complejas como lo es HC1, este método corrige y no se requiere verificación, a diferencia de los otros métodos de transformación de variables.</p></li>
<li><p><strong>Usar el paquete gls:</strong> generalized leat squares</p></li>
</ul>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="modelos-lineales.html#cb153-1" tabindex="-1"></a><span class="co"># vcov matriz de covarianzas. Hay varias opciones HC1, HC2, etc. Esto es un métdo de sandwich con un estimador de White, más sencillo en bayesiana</span></span>
<span id="cb153-2"><a href="modelos-lineales.html#cb153-2" tabindex="-1"></a></span>
<span id="cb153-3"><a href="modelos-lineales.html#cb153-3" tabindex="-1"></a><span class="fu">coeftest</span>(regresion_simple, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(regresion_simple, <span class="st">&quot;HC1&quot;</span>))</span></code></pre></div>
<pre><code>## 
## t test of coefficients:
## 
##              Estimate Std. Error t value  Pr(&gt;|t|)    
## (Intercept) -1.046112   0.111866 -9.3515 2.954e-10 ***
## dap          0.056475   0.003530 15.9988 6.296e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Se pueden conocer los intervalos de confianza:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="modelos-lineales.html#cb155-1" tabindex="-1"></a><span class="fu">coefci</span>(regresion_simple, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(regresion_simple, <span class="st">&quot;HC1&quot;</span>))</span></code></pre></div>
<pre><code>##                   2.5 %     97.5 %
## (Intercept) -1.27490335 -0.8173214
## dap          0.04925587  0.0636951</code></pre>
<p>Acá se interpreta el tamño del efecto usando el IC: por cada 1 <span class="math inline">\(cm\)</span> que aumenta el <span class="math inline">\(dap\)</span>, el <span class="math inline">\(volumen\)</span> de los árboles aumentarán entre 0.04925587 y 0.0636951 <span class="math inline">\(m^{3}\)</span>.</p>
<p>Ahora podemos realizar un gráfico de nuestro modelo pero teniendo en consideración:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="modelos-lineales.html#cb157-1" tabindex="-1"></a><span class="fu">plot_model</span>(regresion_simple, <span class="at">type =</span> <span class="st">&quot;pred&quot;</span>, <span class="at">vcov.type =</span> <span class="st">&quot;HC1&quot;</span>)</span></code></pre></div>
<p><img src="AnalisisdeDatos_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<p>Este es el gráfico del modelo con un intervalode confianza al 95%</p>
<p><strong>La intepretación del modelo sería la siguiente:</strong></p>
<p>La variable dap presentó una relación positiva con el volumen y se considera estadísticamente signigificativa (<span class="math inline">\(\alpha = 0.05\)</span>), por cada <span class="math inline">\(1 cm\)</span> en el incremento del <span class="math inline">\(dap\)</span>, el <span class="math inline">\(volumen\)</span> se incrementó <span class="math inline">\(0.06\)</span>, <span class="math inline">\(EE = 0.004\)</span>, <span class="math inline">\(95% IC [0.05, 0.06]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>. El modelo explicó una parte sustancial de la varianza (<span class="math inline">\(R^2 = 0.93\)</span>).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="exploracion-y-visualización-de-datos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="herramientas-para-visualizar-datos.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
